import { chromium } from "@playwright/test";
const base = "http://localhost:8080";
const b = await chromium.launch();
const ctx = await b.newContext();
const p = await ctx.newPage();
const go = (u) => p.goto(base + u, { waitUntil: "networkidle", timeout: 180000 });
const submit = async (name, url) => { const [r] = await Promise.all([p.waitForResponse((r) => r.url().includes(url), { timeout: 120000 }), p.getByRole("button", { name }).click()]); return r.status() + " " + (await r.text()).slice(0, 120); };

await go("/connexion");
await p.locator("#login").fill("contact@froid-atlas.ma");
await p.locator("#password").fill("change-me-reseller");
await p.getByRole("button", { name: "Se connecter" }).click();
await p.waitForURL(/commande-rapide/, { timeout: 120000 });
await p.waitForLoadState("networkidle");
const ref = p.getByRole("combobox", { name: "Référence" }).first();
await ref.fill("CUIV00");
await p.getByRole("option").first().waitFor({ timeout: 60000 });
await p.getByRole("option").first().dispatchEvent("mousedown");
await p.getByRole("button", { name: "Coller une liste de références" }).click();
await p.locator("textarea").fill("GAZ00042 2\nCUIV0099 1");
const [pr] = await Promise.all([p.waitForResponse((r) => r.url().includes("/api/pro/resolve"), { timeout: 120000 }), p.getByRole("button", { name: "Ajouter à la liste" }).click()]);
console.log("resolve", pr.status());
await p.waitForTimeout(500);
console.log("summary", (await p.locator("aside").innerText()).replace(/\n+/g, " | "));
await p.getByRole("button", { name: "Ajouter au panier" }).first().click();
await p.waitForTimeout(500);
console.log("cart cookie", (await ctx.cookies()).find((c) => c.name === "cm_cart")?.value, "token cookie httpOnly", (await ctx.cookies()).find((c) => c.name === "cm_token")?.httpOnly);
await p.getByRole("button", { name: "Se déconnecter" }).first().click();
await p.waitForURL(/connexion/, { timeout: 60000 });
console.log("after logout token", (await ctx.cookies()).find((c) => c.name === "cm_token")?.value ?? "none");
await b.close();
